[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_dex = "937LDtW3Dkgtb2gVVyzQf64pRcPMyyTt4rn4tpyFECtS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/simonli/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
