[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_dex = "84MC7wnQLJroocUoD8iAzMQmEyKCrVSFJNVLruw5dwz9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/simonli/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
